### ISSUE TITLE
Support for home_timeline ?

### ISSUE THREAD

**Issue by Amar-Chaudhari** [ckoepp/TwitterSearch#30]
Hey,

Does this library support retrieving tweets from statuses/home_timeline ?

Thanks

**Comment by ckoepp** [comment]
No it doesn't. Only the search API and [user timelines](https://dev.twitter.com/rest/reference/get/statuses/user_timeline) are supported.

It should be easy to add the home timeline as well, though. Although I think that most people would use a twitter client library for such things.
