### ISSUE TITLE
query operators does not work

### ISSUE THREAD

**Issue by fjcaro** [ckoepp/TwitterSearch#33]
Hello, I am having troubles using query operators. For example the query '"michelle bachelet"' throws tweets including not only "michelle bachelet" exact phrase, but also tweets containing only "michelle", others containing only "bachelet", and others containing both "michelle" and "bachelet" with different distances between those two words. In general AND, OR and exact phrase queries throws all three types of results.

I will appreciate any help with this issue.

**Comment by ckoepp** [comment]
You would need to enter _"michelle bachelet"_ (including quotes!).

The Twitter Search API treats the same phrase without quotes as _michelle_ OR _bachelet_. You can actually try it out at [twitter.com/search](https://twitter.com/search?q=%22barak%20obama%22&src=typd)
